### ISSUE TITLE
Add command preprocessing (like in python version)

### ISSUE THREAD

**Issue by kstep** [systemd-cron/systemd-crontab-generator#20]
Python version contains code to different edge-cases of command field:

- shell-specific behavior for different shells (ksh, bash, csh, etc),
- stdout redirection
- testing for files/dirs existance
- too complex commands (put to external shell file)

Rust version should also check for these edge cases.

**Comment by a-detiste** [comment]
> too complex commands (put to external shell file)

If you manage to understand systemd`s code that escape & unescape strings, you could get rid of this hack.

**Comment by kstep** [comment]
I'm thinking about simplifying this code but stripping down to one case: just create a shell script accompanying service unit with the command and be done with it. Is it possible? Do `standardoutput` and `testremoved` thingies really necessary?

**Comment by a-detiste** [comment]
I guess getting rid of an extraneous 'sh -c "xxx" ' when `os.path.isfile(common)` make the generated files & pstree output cleaner, the rest is moslty there to help cope with Debian slowish systemd transition (="just make pretend systemd timers doesn't exist"); not much needed for someone who use a custom /etc/crontab

**Comment by kstep** [comment]
I ended up with stripped own version of command analysis:

1. if command is a file, just leave it as is,
2. if command is not a file, then create shell script with the command, and use this script's name instead of original command.

I think it should cover all cases well enough without increasing complexity too much.
Generate units function is already bloated and should eventually be refactored, so I don't want to bloat it even more.

**Comment by kstep** [comment]
If you don't see problems with this implementation, I'd close the issue. What do you say?

**Comment by a-detiste** [comment]
I don't know rust,but it seems perfect.

2015-07-05 22:26 UTC+02:00, Konstantin Stepanov <notifications@github.com>:

**Comment by kstep** [comment]
It's not actually about the rust, it's more about logic, which was polished out by you for the very long time, that's why I asked you for a review =)

So I close the issue for now.
