### ISSUE TITLE
Add reboot lock file to track daemon reload

### ISSUE THREAD

**Issue by kstep** [systemd-cron/systemd-crontab-generator#23]
Question (to @a-detiste, @dbent, maybe others): I *think* I understand this piece of logic (check for `REBOOT_FILE` and create it if `/var` is mounted, to avoid rerunning on-boot jobs when systemd is just reloading), but in case I got it wrong, please elaborate reasons behind this design decision. Thank you.

**Comment by a-detiste** [comment]
> avoid rerunning on-boot jobs when systemd is just reloading

That's it, by re-using Vixie cron's lock file, it also ensure the on-boot jobs are not run on the moment cron is replaced by systemd-cron.

If /var is not available in early boot, it's better to run the on-boot jobs during the forced daemon-reload.

This was discussed on `systemd-devel`, everyone complained it was rather ugly, but there wasn't any better solutino found.

Most people are used to run *daemons* from on-boot job, but this is explicitely forbiden when using `Type=oneshot`; I guess these people should really think about writing native systemd units or move their stuff to `/etc/rc.local`. There is now also `/etc/tmpfiles.d`; so there remain little use cases for on-boot cron job.

**Comment by kstep** [comment]
Thank you for explanation, you answered my question in greater details than I could anticipate.
